# Operacje na macierzach - rozwiązywanie układów równań liniowych

## 1. Mnożenie macierzy Numpy

### Tworzenie macierzy

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4], dtype=float)
print(a)
print(a.dtype)

[1. 2. 3. 4.]
float64


In [3]:
a.reshape(2,2)
print(a)

[1. 2. 3. 4.]


In [4]:
a = a.reshape(2,2)
print(a)

[[1. 2.]
 [3. 4.]]


In [5]:
b = np.array([0, 3, 5, 7], dtype=float)
b = b.reshape(2,2)
print(b)

[[0. 3.]
 [5. 7.]]


### Mnożenie "pozycyjne" (macierz której elementami są iloczyny odpowiadających im elementów obydwu mnożonych macierzy)

In [6]:
x = a*b
print(x)

[[ 0.  6.]
 [15. 28.]]


### Mnożenie macierzowe (wiersze przez kolumny)

In [7]:
x2 = a.dot(b)
print(x2)

[[10. 17.]
 [20. 37.]]


### Wyznacznik macierzy

In [8]:
d = np.linalg.det(x2)
print(d)

29.99999999999999


## 2. Wyznaczanie macierzy odwrotnej metodą Gaussa-Jordana i jej zastosowanie do rozwiązywania układów równań liniowych

In [1]:
import numpy as np
def inv_matrix_3x3(a):
    '''
    Return invertible matrix 3x3 using Gauss-Jordan method.
    
    Arguments
    ---------
    a : numpy array, 3x3 size, float type values
        Start matrix.
    
    Returns
    -------
    numpy array, 3x3 size, float type values
        Calculated invertible matrix (with some error).
    
    '''
    
    b = np.zeros([len(a), len(a)], dtype = float)
    np.fill_diagonal(b, 1)
    
    #step 1
    temp = a[0, 0]
    a[0] = a[0] / temp
    b[0] = b[0] / temp
    
    #step 2
    temp = a[1, 0]
    a[1] = a[1] - (temp * a[0])
    b[1] = b[1] - (temp * b[0])
    
    temp = a[2, 0]
    a[2] = a[2] - (temp * a[0])
    b[2] = b[2] - (temp * b[0])
    
    #step 3
    temp = a[1, 1]
    a[1] = a[1] / temp
    b[1] = b[1] / temp
    
    temp = a[0, 1]
    a[0] = a[0] - a[1] * temp
    b[0] = b[0] - b[1] * temp

    temp = a[2, 1]
    a[2] = a[2] - a[1] * temp
    b[2] = b[2] - b[1] * temp
    
    #step 4
    temp = a[2, 2]
    a[2] = a[2] / temp
    b[2] = b[2] / temp
    
    temp = a[0, 2]
    a[0] = a[0] - a[2] * temp
    b[0] = b[0] - b[2] * temp
    
    temp = a[1, 2]
    a[1] = a[1] - a[2] * temp
    b[1] = b[1] - b[2] * temp
    
    return b


In [2]:
def inv_matrix(matrix):
    '''
    Return invertible matrix using Gauss-Jordan method.
    
    Arguments
    ---------
    matrix : numpy array, any size, float type values
        Start matrix.
    
    Returns
    -------
    numpy array, dimensions as start matrix, float type values
        Calculated invertible matrix (with some error).
    
    '''
    n = len(matrix[0])
    
    #matrix n x 2n. 
    #left part filled with argument's values
    #right part is a diagonal matrix
    b = np.zeros([n, n], dtype = float)
    np.fill_diagonal(b, 1)
    a = np.concatenate([matrix, b], axis = 1)

    #step 1: Gauss-Jordan elimination
    for i in range(n):
        for j in range(n):
            if i != j:
                ratio = a[j, i] / a[i, i]

                for k in range(2 * n):
                    a[j, k] = a[j, k] - ratio * a[i, k]
                    
    #step 2: repair main diagonal
    for i in range(n):
        divisor = a[i, i]
        for j in range(2 * n):
            a[i, j] = a[i, j] / divisor
    return a[:, n:]

In [3]:
matrix1 = np.array([2, 1, 1, 1, 2, 1, 1, 1, 2], dtype=float).reshape(3,3)
print(inv_matrix_3x3(matrix1))

matrix1 = np.array([2, 1, 1, 1, 2, 1, 1, 1, 2], dtype=float).reshape(3,3)
print(inv_matrix(matrix1))

[[ 0.75 -0.25 -0.25]
 [-0.25  0.75 -0.25]
 [-0.25 -0.25  0.75]]
[[ 0.75 -0.25 -0.25]
 [-0.25  0.75 -0.25]
 [-0.25 -0.25  0.75]]


In [4]:
matrix2 = np.array([1, 1, 3, 1, 3, -3, -2, -4, -4], dtype=float).reshape(3,3)
print(inv_matrix_3x3(matrix2))

matrix2 = np.array([1, 1, 3, 1, 3, -3, -2, -4, -4], dtype=float).reshape(3,3)
print(inv_matrix(matrix2))

[[ 3.    1.    1.5 ]
 [-1.25 -0.25 -0.75]
 [-0.25 -0.25 -0.25]]
[[ 3.    1.    1.5 ]
 [-1.25 -0.25 -0.75]
 [-0.25 -0.25 -0.25]]


In [5]:
def linear_equations_Gauss(a, b):
    '''
    Return system of linear equations's solutions.
    
    Arguments
    ---------
    a : numpy array, float type values
        Main matrix with coefficients.
    b : numpy array, float type values
        Vector with constant terms.
     
    Returns
    -------
    numpy array, dimensions as matrix b, float type values
        Solution with X values.
    
    '''
    invertible_matrix = inv_matrix(a)
    return invertible_matrix.dot(b)

In [6]:
'''
2x - 2y + 1z = -3
1x + 3y - 2z = 1
3x - 1y - 1z = 2
'''
a = np.array([2, -2, 1, 1, 3, -2, 3, -1, -1], dtype=float)
a = a.reshape(3, 3)

b = np.array([-3, 1, 2], dtype=float)
b = b.reshape(3, 1)

linear_equations_Gauss(a, b)

array([[-1.4],
       [-2. ],
       [-4.2]])

In [7]:
'''
2x + 0y + 1z = 2
1x - 3y + 0z = 1
1x + 1y - 2z = 0
'''
a = np.array([2, 0, 1, 1, -3, 0, 1, 1, -2], dtype=float)
a = a.reshape(3, 3)

b = np.array([2, 1, 0], dtype=float)
b = b.reshape(3, 1)
linear_equations_Gauss(a, b)

array([[ 0.8125],
       [-0.0625],
       [ 0.375 ]])

In [8]:
'''
3x-3y-3z=-3
2x+y+2z=6
-x+2y+2z=4
'''
a = np.array(
[
    [3,-3,-3],
    [2,1,2],
    [-1,2,2]
])
b = np.array(
[
    [-3],
    [6],
    [4]
])
linear_equations_Gauss(a, b)

array([[ 2.],
       [ 4.],
       [-1.]])

In [9]:
'''
3x-3y-2z=-1
4x-y+z=7
-1x+4y+4z=2
'''
a = np.array(
[
    [3,-3,-2],
    [4,-1,1],
    [-1,4,4]
])
b = np.array(
[
    [-1],
    [7],
    [2]
])
linear_equations_Gauss(a, b)

array([[ -8.66666667],
       [-21.66666667],
       [ 20.        ]])

In [18]:
'''
x+7y+3v+5u=16
8x+4y+6v+2u=-16
2x+6y+4v+8u=16
5x+3y+7v+1u=-16
'''
a = np.array(
[
    [1,7,3,5],
    [8,4,6,2],
    [2,6,4,8],
    [5,3,7,1]
])
b = np.array(
[
    [16],
    [-16],
    [16],
    [-16]
])
linear_equations_Gauss(a, b)

array([[-2.],
       [ 2.],
       [-2.],
       [ 2.]])